Split the interface version into the protocol and pre-release versions
stellar/stellar-xdr-next pull request #179
Opened 2024-04-03 21:59 UTC by leighmcculloch

### What
Split the interface version into the protocol and pre-release versions

### Why
...

2024-04-05 16:43 UTC, graydon requested changes

2024-04-05 16:43 UTC, graydon commented on Stellar-contract-env-meta.x
> +    uint32 interfaceVersion;
```suggestion
    uint32 protocolVersion;
```

2024-04-05 16:43 UTC, graydon commented on Stellar-contract-env-meta.x
> +    uint32 interfaceVersion;
```suggestion
    uint32 preReleaseVersion;
```

2024-10-15 12:28 UTC, leighmcculloch commented
Superseded by:
- https://github.com/stellar/stellar-xdr/pull/213
- https://github.com/stellar/stellar-xdr/pull/212

2024-10-15 12:28 UTC, closed without merging